name: Cmarkup
version: 0.1.0
main: me.qualterz.minecraft.cmarkup.plugin.CmarkupPlugin
description: Markup containers with ease
author: qualterz
website: https://github.com/qualterz/cmarkup
api-version: '1.20'

commands:
  title:
    description: Set title for container
  open:
    description: Open markup for editing or reviewing
  create:
    description: Create markup entry
  delete:
    description: Delete markup entry
  list:
    description: List of stored markup entries
  slots:
    description: List of stored markup slots
  types:
    description: List of available container types
